return {
  {
    name = "cast",
    kind = "cast",
    inputs = {"x:array", "dtype:dtype"},
    outputs = {"out:array"},
    promote = "none",
    broadcast = false,
    dtypes = {"bool", "u8", "i8", "i16", "i32", "i64", "f16", "bf16", "f32", "f64", "c32", "c64", "u16", "u32", "u64"},
    host = {strategy = "cast"},
    device = {strategy = "cast"},
  },
  {
    name = "copy",
    kind = "manipulation",
    inputs = {"x:array"},
    outputs = {"out:array"},
    promote = "identity",
    broadcast = false,
    dtypes = {"bool", "u8", "i8", "i16", "i32", "i64", "f16", "bf16", "f32", "f64", "c32", "c64", "u16", "u32", "u64"},
    host = {strategy = "contiguous_copy"},
    device = {strategy = "contiguous_copy"},
  },
  {
    name = "contiguous",
    kind = "manipulation",
    inputs = {"x:array"},
    outputs = {"out:array"},
    promote = "identity",
    broadcast = false,
    dtypes = {"bool", "u8", "i8", "i16", "i32", "i64", "f16", "bf16", "f32", "f64", "c32", "c64", "u16", "u32", "u64"},
    host = {strategy = "contiguous_copy"},
    device = {strategy = "contiguous_copy"},
  },
}
