return {
  {
    name = "full",
    kind = "creation",
    inputs = {"shape:shape", "value:scalar", "dtype:dtype", "place:place"},
    outputs = {"out:array"},
    promote = "none",
    broadcast = false,
    dtypes = {"bool", "i32", "i64", "f32", "f64", "c32", "c64"},
    host = {strategy = "fill"},
    device = {strategy = "fill"},
  },
  {
    name = "zeros",
    kind = "creation",
    inputs = {"shape:shape", "dtype:dtype", "place:place"},
    outputs = {"out:array"},
    promote = "none",
    broadcast = false,
    dtypes = {"bool", "i32", "i64", "f32", "f64", "c32", "c64"},
    host = {strategy = "full_zero"},
    device = {strategy = "full_zero"},
  },
  {
    name = "ones",
    kind = "creation",
    inputs = {"shape:shape", "dtype:dtype", "place:place"},
    outputs = {"out:array"},
    promote = "none",
    broadcast = false,
    dtypes = {"bool", "i32", "i64", "f32", "f64", "c32", "c64"},
    host = {strategy = "full_one"},
    device = {strategy = "full_one"},
  },
}
