return {
  {
    name = "add",
    kind = "binary_elementwise",
    inputs = {"a:array", "b:array"},
    outputs = {"out:array"},
    promote = "numeric",
    broadcast = true,
    dtypes = {"bool", "i32", "i64", "f32", "f64", "c32", "c64"},
    host = {expr = "a + b"},
    device = {expr = "a + b"},
  },
  {
    name = "sub",
    kind = "binary_elementwise",
    inputs = {"a:array", "b:array"},
    outputs = {"out:array"},
    promote = "numeric",
    broadcast = true,
    dtypes = {"i32", "i64", "f32", "f64", "c32", "c64"},
    host = {expr = "a - b"},
    device = {expr = "a - b"},
  },
  {
    name = "mul",
    kind = "binary_elementwise",
    inputs = {"a:array", "b:array"},
    outputs = {"out:array"},
    promote = "numeric",
    broadcast = true,
    dtypes = {"bool", "i32", "i64", "f32", "f64", "c32", "c64"},
    host = {expr = "a * b"},
    device = {expr = "a * b"},
  },
  {
    name = "div",
    kind = "binary_elementwise",
    inputs = {"a:array", "b:array"},
    outputs = {"out:array"},
    promote = "numeric",
    broadcast = true,
    dtypes = {"f32", "f64", "c32", "c64"},
    host = {expr = "a / b"},
    device = {expr = "a / b"},
  },
  {
    name = "equal",
    kind = "binary_elementwise",
    inputs = {"a:array", "b:array"},
    outputs = {"out:array"},
    promote = "comparison",
    broadcast = true,
    dtypes = {"bool", "i32", "i64", "f32", "f64", "c32", "c64"},
    host = {expr = "a == b"},
    device = {expr = "a == b"},
  },
  {
    name = "not_equal",
    kind = "binary_elementwise",
    inputs = {"a:array", "b:array"},
    outputs = {"out:array"},
    promote = "comparison",
    broadcast = true,
    dtypes = {"bool", "i32", "i64", "f32", "f64", "c32", "c64"},
    host = {expr = "a != b"},
    device = {expr = "a != b"},
  },
  {
    name = "greater",
    kind = "binary_elementwise",
    inputs = {"a:array", "b:array"},
    outputs = {"out:array"},
    promote = "comparison",
    broadcast = true,
    dtypes = {"bool", "i32", "i64", "f32", "f64"},
    host = {expr = "a > b"},
    device = {expr = "a > b"},
  },
  {
    name = "less",
    kind = "binary_elementwise",
    inputs = {"a:array", "b:array"},
    outputs = {"out:array"},
    promote = "comparison",
    broadcast = true,
    dtypes = {"bool", "i32", "i64", "f32", "f64"},
    host = {expr = "a < b"},
    device = {expr = "a < b"},
  },
}
