return {
  {
    name = "sum",
    kind = "reduction",
    inputs = {"x:array", "axis:int?", "keepdim:bool"},
    outputs = {"out:array"},
    promote = "identity",
    broadcast = false,
    dtypes = {"bool", "i32", "i64", "f32", "f64"},
    host = {strategy = "reduce_sum"},
    device = {strategy = "reduce_sum"},
  },
  {
    name = "mean",
    kind = "reduction",
    inputs = {"x:array", "axis:int?", "keepdim:bool"},
    outputs = {"out:array"},
    promote = "floating",
    broadcast = false,
    dtypes = {"i32", "i64", "f32", "f64"},
    host = {strategy = "reduce_mean"},
    device = {strategy = "reduce_mean"},
  },
  {
    name = "min",
    kind = "reduction",
    inputs = {"x:array", "axis:int?", "keepdim:bool"},
    outputs = {"out:array"},
    promote = "identity",
    broadcast = false,
    dtypes = {"bool", "i32", "i64", "f32", "f64"},
    host = {strategy = "reduce_min"},
    device = {strategy = "reduce_min"},
  },
  {
    name = "max",
    kind = "reduction",
    inputs = {"x:array", "axis:int?", "keepdim:bool"},
    outputs = {"out:array"},
    promote = "identity",
    broadcast = false,
    dtypes = {"bool", "i32", "i64", "f32", "f64"},
    host = {strategy = "reduce_max"},
    device = {strategy = "reduce_max"},
  },
}
