return {
  {
    name = "neg",
    kind = "unary_elementwise",
    inputs = {"x:array"},
    outputs = {"out:array"},
    promote = "identity",
    dtypes = {"i32", "i64", "f32", "f64", "c32", "c64"},
    host = {expr = "-x"},
    device = {expr = "-x"},
  },
  {
    name = "abs",
    kind = "unary_elementwise",
    inputs = {"x:array"},
    outputs = {"out:array"},
    promote = "identity",
    dtypes = {"i32", "i64", "f32", "f64", "c32", "c64"},
    host = {expr = "abs(x)"},
    device = {expr = "abs(x)"},
  },
  {
    name = "exp",
    kind = "unary_elementwise",
    inputs = {"x:array"},
    outputs = {"out:array"},
    promote = "floating",
    dtypes = {"f32", "f64", "c32", "c64"},
    host = {expr = "exp(x)"},
    device = {expr = "exp(x)"},
  },
  {
    name = "log",
    kind = "unary_elementwise",
    inputs = {"x:array"},
    outputs = {"out:array"},
    promote = "floating",
    dtypes = {"f32", "f64", "c32", "c64"},
    host = {expr = "log(x)"},
    device = {expr = "log(x)"},
  },
  {
    name = "sqrt",
    kind = "unary_elementwise",
    inputs = {"x:array"},
    outputs = {"out:array"},
    promote = "floating",
    dtypes = {"f32", "f64"},
    host = {expr = "sqrt(x)"},
    device = {expr = "sqrt(x)"},
  },
}
