local M = {}

local function guard_name()
  return "INSIGHT_GENERATED_KERNEL_PLAN_H"
end

local function join(values, sep)
  local out = {}
  for i, value in ipairs(values or {}) do
    out[i] = tostring(value)
  end
  return table.concat(out, sep or ", ")
end

local function quoted(value)
  return string.format("%q", tostring(value))
end

local function strategy(op, adapter)
  local impl = op[adapter] or {}
  if impl.expr then
    return "expression:" .. impl.expr
  end
  return "strategy:" .. tostring(impl.strategy or "fallback")
end

function M.render(ops)
  local guard = guard_name()
  local lines = {
    "// Generated by tools/codegen/gen.lua. Do not edit by hand.",
    "#ifndef " .. guard,
    "#define " .. guard,
    "",
    "namespace ins::generated {",
    "struct KernelPlan {",
    "  const char *name;",
    "  const char *kind;",
    "  const char *promotion;",
    "  const char *dtypes;",
    "  bool broadcast;",
    "  const char *host;",
    "  const char *device;",
    "};",
    "",
    "inline constexpr KernelPlan kernel_plans[] = {",
  }
  for _, op in ipairs(ops) do
    lines[#lines + 1] = string.format(
      "  {%s, %s, %s, %s, %s, %s, %s},",
      quoted(op.name), quoted(op.kind), quoted(op.promote or "none"),
      quoted(join(op.dtypes, "|")), op.broadcast == true and "true" or "false",
      quoted(strategy(op, "host")), quoted(strategy(op, "device")))
  end
  lines[#lines + 1] = "};"
  lines[#lines + 1] = "inline constexpr unsigned kernel_plan_count = " .. #ops .. ";"
  lines[#lines + 1] = "} // namespace ins::generated"
  lines[#lines + 1] = ""
  lines[#lines + 1] = "#endif // " .. guard
  return table.concat(lines, "\n")
end

function M.render_markdown(ops)
  local lines = {
    "# Generated backend-neutral kernel plan",
    "",
    "One Lua schema record is shared by host and device adapters.",
    "",
    "| Operator | Kind | Promotion | Dtypes | Broadcast | Host adapter | Device adapter |",
    "|---|---|---|---|---|---|---|",
  }
  for _, op in ipairs(ops) do
    lines[#lines + 1] = string.format(
      "| `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` |",
      op.name, op.kind, op.promote or "none", join(op.dtypes, ", "),
      op.broadcast == true and "yes" or "no", strategy(op, "host"),
      strategy(op, "device"))
  end
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

return M
