local M = {}

local function sorted_keys(tbl)
  local keys = {}
  for key in pairs(tbl) do
    keys[#keys + 1] = key
  end
  table.sort(keys)
  return keys
end

local function join(values, sep)
  local out = {}
  for i, value in ipairs(values) do
    out[i] = tostring(value)
  end
  return table.concat(out, sep or ", ")
end

local function write_line(lines, text)
  lines[#lines + 1] = text or ""
end

function M.render(ops)
  local by_kind = {}
  for _, op in ipairs(ops) do
    by_kind[op.kind] = by_kind[op.kind] or {}
    by_kind[op.kind][#by_kind[op.kind] + 1] = op
  end

  local lines = {}
  write_line(lines, "# Insight generated operator manifest")
  write_line(lines)
  write_line(lines, "This file is generated by `tools/codegen/gen.lua`.")
  write_line(lines)
  write_line(lines, string.format("Total ops: %d", #ops))

  for _, kind in ipairs(sorted_keys(by_kind)) do
    table.sort(by_kind[kind], function(a, b)
      return a.name < b.name
    end)
    write_line(lines)
    write_line(lines, "## " .. kind)
    for _, op in ipairs(by_kind[kind]) do
      write_line(lines, string.format("- `%s`: inputs=(%s), outputs=(%s), dtypes=(%s), promote=%s, broadcast=%s",
        op.name,
        join(op.inputs or {}),
        join(op.outputs or {}),
        join(op.dtypes or {}),
        op.promote or "none",
        tostring(op.broadcast == true)))
    end
  end

  write_line(lines)
  return table.concat(lines, "\n")
end

return M
