local M = {}

local function guard_name(module_name)
  return "INSIGHT_GENERATED_" .. string.upper(module_name:gsub("[^%w]", "_")) .. "_H"
end

local function write_line(lines, text)
  lines[#lines + 1] = text or ""
end

function M.render(module_name, ops)
  table.sort(ops, function(a, b)
    return a.name < b.name
  end)

  local guard = guard_name(module_name)
  local lines = {}
  write_line(lines, "// Generated by tools/codegen/gen.lua. Do not edit by hand.")
  write_line(lines, "#ifndef " .. guard)
  write_line(lines, "#define " .. guard)
  write_line(lines)
  write_line(lines, "namespace ins::generated {")
  write_line(lines)
  write_line(lines, "struct OpSchemaStub {")
  write_line(lines, "  const char *name;")
  write_line(lines, "  const char *kind;")
  write_line(lines, "  const char *promote;")
  write_line(lines, "  bool broadcast;")
  write_line(lines, "};")
  write_line(lines)
  write_line(lines, "inline constexpr OpSchemaStub " .. module_name .. "_ops[] = {")
  for _, op in ipairs(ops) do
    write_line(lines, string.format("    {\"%s\", \"%s\", \"%s\", %s},",
      op.name,
      op.kind,
      op.promote or "none",
      op.broadcast and "true" or "false"))
  end
  write_line(lines, "};")
  write_line(lines)
  write_line(lines, "} // namespace ins::generated")
  write_line(lines)
  write_line(lines, "#endif // " .. guard)
  return table.concat(lines, "\n")
end

return M
