local M = {}

local function quoted(value)
  return string.format("%q", tostring(value))
end

local function strategy(op, adapter)
  local impl = op[adapter] or {}
  if impl.expr then
    return "expression:" .. impl.expr
  end
  return "strategy:" .. tostring(impl.strategy or "fallback")
end

function M.render(ops)
  local lines = {
    "// Generated by tools/codegen/gen.lua. Do not edit by hand.",
    "#ifndef INSIGHT_GENERATED_SOURCE_MANIFEST_H",
    "#define INSIGHT_GENERATED_SOURCE_MANIFEST_H",
    "",
    "namespace ins::generated {",
    "struct SourceManifestEntry {",
    "  const char *name;",
    "  const char *kind;",
    "  const char *host_adapter;",
    "  const char *device_adapter;",
    "};",
    "",
    "inline constexpr SourceManifestEntry source_manifest[] = {",
  }
  for _, op in ipairs(ops) do
    lines[#lines + 1] = string.format(
      "  {%s, %s, %s, %s},", quoted(op.name), quoted(op.kind),
      quoted(strategy(op, "host")), quoted(strategy(op, "device")))
  end
  lines[#lines + 1] = "};"
  lines[#lines + 1] = "inline constexpr unsigned source_manifest_count = " .. #ops .. ";"
  lines[#lines + 1] = "} // namespace ins::generated"
  lines[#lines + 1] = ""
  lines[#lines + 1] = "#endif // INSIGHT_GENERATED_SOURCE_MANIFEST_H"
  return table.concat(lines, "\n")
end

function M.render_markdown(ops)
  local lines = {
    "# Generated backend-neutral source manifest",
    "",
    "The build consumes one manifest for host and device adapter selection.",
    "",
    "| Operator | Kind | Host adapter | Device adapter |",
    "|---|---|---|---|",
  }
  for _, op in ipairs(ops) do
    lines[#lines + 1] = string.format(
      "| `%s` | `%s` | `%s` | `%s` |", op.name, op.kind,
      strategy(op, "host"), strategy(op, "device"))
  end
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

return M
