-- Unary CUDA binding tests — aligned with C++ test_unary.cpp
-- Run with:
--   LUA_PATH="bindings/lua/?/init.lua;;" LUA_CPATH="build/bindings/lua/?.so;;"
--   LD_LIBRARY_PATH=build/backends/cpu:build/backends/cuda
--   ~/.luarocks/bin/busted tests/cuda/lua/test_unary.lua

local ok_ins, ins = pcall(require, "_insight")
if not ok_ins then
  print("SKIP: _insight module not available")
  os.exit(0)
end

local ok_gpu = pcall(function()
  ins.init()
end)
if not ok_gpu then
  print("SKIP: GPU backend not available")
  os.exit(0)
end

ins.set_device(ins.GPUPlace(0))

describe("Unary CUDA Tests", function()
  it("abs", function()
    local a = ins.from_table({ -3.0, -1.0, 0.0, 2.0, 4.0 }):to(ins.GPUPlace(0))
    local b = ins.abs(a)
    assert.is_not_nil(b)
    assert.are.equal(5, b.numel)
  end)

  it("sqrt", function()
    local a = ins.from_table({ 1.0, 4.0, 9.0, 16.0 }):to(ins.GPUPlace(0))
    local b = ins.sqrt(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("exp", function()
    local a = ins.from_table({ 0.0, 1.0, 2.0 }):to(ins.GPUPlace(0))
    local b = ins.exp(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("log", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.log(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("sin", function()
    local a = ins.from_table({ 0.0, 0.5, 1.0 }):to(ins.GPUPlace(0))
    local b = ins.sin(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("cos", function()
    local a = ins.from_table({ 0.0, 0.5, 1.0 }):to(ins.GPUPlace(0))
    local b = ins.cos(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("tan", function()
    local a = ins.from_table({ 0.0, 0.5, 1.0 }):to(ins.GPUPlace(0))
    local b = ins.tan(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("floor_ceil_round", function()
    local a = ins.from_table({ 1.2, 2.5, 3.7, -1.3 }):to(ins.GPUPlace(0))
    local f = ins.floor(a)
    local c = ins.ceil(a)
    local r = ins.round(a)
    assert.is_not_nil(f)
    assert.is_not_nil(c)
    assert.is_not_nil(r)
    assert.are.equal(4, f.numel)
  end)

  it("sign", function()
    local a = ins.from_table({ -3.0, -1.0, 0.0, 2.0, 4.0 }):to(ins.GPUPlace(0))
    local b = ins.sign(a)
    assert.is_not_nil(b)
    assert.are.equal(5, b.numel)
  end)

  it("negative", function()
    local a = ins.from_table({ 1.0, -2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.negative(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("square", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0 }):to(ins.GPUPlace(0))
    local b = ins.square(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("reciprocal", function()
    local a = ins.from_table({ 1.0, 2.0, 4.0, 5.0 }):to(ins.GPUPlace(0))
    local b = ins.reciprocal(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("log2_log10", function()
    local a = ins.from_table({ 1.0, 2.0, 8.0, 100.0 }):to(ins.GPUPlace(0))
    local b2 = ins.log2(a)
    local b10 = ins.log10(a)
    assert.is_not_nil(b2)
    assert.is_not_nil(b10)
    assert.are.equal(4, b2.numel)
  end)

  it("asin_acos_atan", function()
    local a = ins.from_table({ -0.5, 0.0, 0.5 }):to(ins.GPUPlace(0))
    local s = ins.asin(a)
    local c = ins.acos(a)
    local t = ins.atan(a)
    assert.is_not_nil(s)
    assert.is_not_nil(c)
    assert.is_not_nil(t)
  end)

  it("sinh_cosh_tanh", function()
    local a = ins.from_table({ -1.0, 0.0, 1.0 }):to(ins.GPUPlace(0))
    local s = ins.sinh(a)
    local c = ins.cosh(a)
    local t = ins.tanh(a)
    assert.is_not_nil(s)
    assert.is_not_nil(c)
    assert.is_not_nil(t)
  end)

  it("deg2rad_rad2deg", function()
    local a = ins.from_table({ 0.0, 90.0, 180.0, 360.0 }):to(ins.GPUPlace(0))
    local r = ins.deg2rad(a)
    assert.is_not_nil(r)
    assert.are.equal(4, r.numel)
    local b = ins.from_table({ 0.0, 1.5707963, 3.1415926, 6.2831853 }):to(ins.GPUPlace(0))
    local d = ins.rad2deg(b)
    assert.is_not_nil(d)
  end)

  it("exp2_expm1_log1p", function()
    local a = ins.from_table({ 0.0, 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    assert.is_not_nil(ins.exp2(a))
    assert.is_not_nil(ins.expm1(a))
    assert.is_not_nil(ins.log1p(a))
  end)

  it("cbrt", function()
    local a = ins.from_table({ 1.0, 8.0, 27.0 }):to(ins.GPUPlace(0))
    local b = ins.cbrt(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("trunc", function()
    local a = ins.from_table({ 1.2, -2.7, 3.5 }):to(ins.GPUPlace(0))
    local b = ins.trunc(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)
end)
