-- Manipulation CUDA binding tests — aligned with C++ test_manipulation.cpp
-- Run with:
--   LUA_PATH="bindings/lua/?/init.lua;;" LUA_CPATH="build/bindings/lua/?.so;;"
--   LD_LIBRARY_PATH=build/backends/cpu:build/backends/cuda
--   ~/.luarocks/bin/busted tests/cuda/lua/test_manipulation.lua

local ok_ins, ins = pcall(require, "_insight")
if not ok_ins then
  print("SKIP: _insight module not available")
  os.exit(0)
end

local ok_gpu = pcall(function()
  ins.init()
end)
if not ok_gpu then
  print("SKIP: GPU backend not available")
  os.exit(0)
end

ins.set_device(ins.GPUPlace(0))

describe("Manipulation CUDA Tests", function()
  it("reshape", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 }):to(ins.GPUPlace(0))
    local b = ins.reshape(a, { 2, 3 })
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
    assert.are.equal(2, b.ndim)
  end)

  it("transpose", function()
    local a = ins.from_table({ { 1, 2, 3 }, { 4, 5, 6 } }):to(ins.GPUPlace(0))
    local b = ins.permute(a, { 1, 0 })
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
  end)

  it("squeeze", function()
    local a = ins.zeros({ 1, 3, 1 }, ins.float64):to(ins.GPUPlace(0))
    local b = ins.squeeze(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("unsqueeze", function()
    local a = ins.zeros({ 3 }, ins.float64):to(ins.GPUPlace(0))
    local b = ins.unsqueeze(a, 0)
    assert.is_not_nil(b)
    assert.are.equal(2, b.ndim)
  end)

  it("concat", function()
    local a = ins.from_table({ 1.0, 2.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 3.0, 4.0 }):to(ins.GPUPlace(0))
    local c = ins.concat({ a, b })
    assert.is_not_nil(c)
    assert.are.equal(4, c.numel)
  end)

  it("split", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 }):to(ins.GPUPlace(0))
    local parts = ins.split(a, 3, 0)
    assert.is_not_nil(parts)
    assert.are.equal(3, #parts)
  end)

  it("tile", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.tile(a, { 2 })
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
  end)

  it("repeat", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins["repeat"](a, 2)
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
  end)

  it("flip", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0 }):to(ins.GPUPlace(0))
    local b = ins.flip(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("roll", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0, 5.0 }):to(ins.GPUPlace(0))
    local b = ins.roll(a, 2)
    assert.is_not_nil(b)
    assert.are.equal(5, b.numel)
  end)

  it("pad", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.pad(a, { 2, 3 })
    assert.is_not_nil(b)
    assert.are.equal(8, b.numel)
  end)

  it("diag", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.diag(a)
    assert.is_not_nil(b)
    assert.are.equal(9, b.numel)
    assert.are.equal(2, b.ndim)
  end)

  it("tril", function()
    local a = ins.ones({ 3, 3 }, ins.float64):to(ins.GPUPlace(0))
    local b = ins.tril(a)
    assert.is_not_nil(b)
    assert.are.equal(9, b.numel)
  end)

  it("triu", function()
    local a = ins.ones({ 3, 3 }, ins.float64):to(ins.GPUPlace(0))
    local b = ins.triu(a)
    assert.is_not_nil(b)
    assert.are.equal(9, b.numel)
  end)

  it("diff", function()
    local a = ins.from_table({ 1.0, 3.0, 6.0, 10.0 }):to(ins.GPUPlace(0))
    local b = ins.diff(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("swapaxes", function()
    local a = ins.ones({ 2, 3, 4 }, ins.float64):to(ins.GPUPlace(0))
    local b = ins.swapaxes(a, 0, 2)
    assert.is_not_nil(b)
    assert.are.equal(24, b.numel)
  end)

  it("moveaxis", function()
    local a = ins.ones({ 2, 3, 4 }, ins.float64):to(ins.GPUPlace(0))
    local b = ins.moveaxis(a, 0, 2)
    assert.is_not_nil(b)
    assert.are.equal(24, b.numel)
  end)

  it("fliplr", function()
    local a = ins.from_table({ { 1, 2 }, { 3, 4 } }):to(ins.GPUPlace(0))
    local b = ins.fliplr(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("flipud", function()
    local a = ins.from_table({ { 1, 2 }, { 3, 4 } }):to(ins.GPUPlace(0))
    local b = ins.flipud(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("rot90", function()
    local a = ins.from_table({ { 1, 2 }, { 3, 4 } }):to(ins.GPUPlace(0))
    local b = ins.rot90(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("flatten", function()
    local a = ins.ones({ 2, 3 }, ins.float64):to(ins.GPUPlace(0))
    local b = ins.flatten(a)
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
    assert.are.equal(1, b.ndim)
  end)

  it("ravel", function()
    local a = ins.ones({ 2, 3 }, ins.float64):to(ins.GPUPlace(0))
    local b = ins.ravel(a)
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
    assert.are.equal(1, b.ndim)
  end)
end)
