-- Linalg CUDA binding tests
-- Run with:
--   LUA_PATH="bindings/lua/?/init.lua;;" LUA_CPATH="build/bindings/lua/?.so;;" \
--   LD_LIBRARY_PATH=build/backends/cpu:build/backends/cuda \
--   ~/.luarocks/bin/busted tests/cuda/lua/test_linalg.lua

local ok_ins, ins = pcall(require, "_insight")
if not ok_ins then
  print("SKIP: _insight module not available")
  os.exit(0)
end

local ok_gpu = pcall(function()
  ins.init()
end)
if not ok_gpu then
  print("SKIP: GPU backend not available")
  os.exit(0)
end

describe("Linalg CUDA Tests", function()
  it("matmul 2x2", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 } }):to(ins.GPUPlace(0))
    local b = ins.from_table({ { 5.0, 6.0 }, { 7.0, 8.0 } }):to(ins.GPUPlace(0))
    local c = ins.matmul(a, b)
    assert.is_not_nil(c)
    assert.are.equal(4, c.numel)
  end)

  it("matmul 3x2 * 2x3", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 }, { 5.0, 6.0 } }):to(ins.GPUPlace(0))
    local b = ins.from_table({ { 1.0, 2.0, 3.0 }, { 4.0, 5.0, 6.0 } }):to(ins.GPUPlace(0))
    local c = ins.matmul(a, b)
    assert.is_not_nil(c)
    assert.are.equal(9, c.numel)
  end)

  it("dot product", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 4.0, 5.0, 6.0 }):to(ins.GPUPlace(0))
    local c = ins.dot(a, b)
    assert.is_not_nil(c)
    assert.are.equal(1, c.numel)
  end)

  it("outer product", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 4.0, 5.0 }):to(ins.GPUPlace(0))
    local c = ins.outer(a, b)
    assert.is_not_nil(c)
    assert.are.equal(6, c.numel)
  end)

  it("norm vector", function()
    local a = ins.from_table({ 3.0, 4.0 }):to(ins.GPUPlace(0))
    local n = ins.norm(a)
    assert.is_not_nil(n)
    assert.are.equal(1, n.numel)
  end)

  it("norm matrix", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 } }):to(ins.GPUPlace(0))
    local n = ins.norm(a)
    assert.is_not_nil(n)
    assert.are.equal(1, n.numel)
  end)

  it("trace", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 } }):to(ins.GPUPlace(0))
    local t = ins.trace(a)
    assert.is_not_nil(t)
    assert.are.equal(1, t.numel)
  end)

  it("det", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 } }):to(ins.GPUPlace(0))
    local d = ins.det(a)
    assert.is_not_nil(d)
    assert.are.equal(1, d.numel)
  end)

  it("inv", function()
    local a = ins.from_table({ { 4.0, 7.0 }, { 2.0, 6.0 } }):to(ins.GPUPlace(0))
    local b = ins.inv(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("solve", function()
    local a = ins.from_table({ { 3.0, 1.0 }, { 1.0, 2.0 } }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 9.0, 8.0 }):to(ins.GPUPlace(0))
    local x = ins.solve(a, b)
    assert.is_not_nil(x)
    assert.are.equal(2, x.numel)
  end)

  it("svd", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 }, { 5.0, 6.0 } }):to(ins.GPUPlace(0))
    local u, s, vt = ins.svd(a)
    assert.is_not_nil(s)
    assert.are.equal(2, s.numel)
  end)

  it("eigh", function()
    local a = ins.from_table({ { 4.0, 2.0 }, { 2.0, 3.0 } }):to(ins.GPUPlace(0))
    local w, v = ins.eigh(a)
    assert.is_not_nil(w)
    assert.are.equal(2, w.numel)
  end)

  it("cholesky", function()
    local a = ins.from_table({ { 4.0, 2.0 }, { 2.0, 3.0 } }):to(ins.GPUPlace(0))
    local l = ins.cholesky(a)
    assert.is_not_nil(l)
    assert.are.equal(4, l.numel)
  end)

  it("qr", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 }, { 5.0, 6.0 } }):to(ins.GPUPlace(0))
    local q, r = ins.qr(a)
    assert.is_not_nil(q)
    assert.is_not_nil(r)
  end)

  it("lstsq", function()
    local a = ins.from_table({ { 1.0, 1.0 }, { 1.0, 2.0 }, { 1.0, 3.0 } }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 1.0, 2.0, 2.0 }):to(ins.GPUPlace(0))
    local x = ins.lstsq(a, b)
    assert.is_not_nil(x)
    assert.are.equal(2, x.numel)
  end)

  it("cond", function()
    local a = ins.from_table({ { 1.0, 0.0 }, { 0.0, 2.0 } }):to(ins.GPUPlace(0))
    local c = ins.cond(a)
    assert.is_not_nil(c)
    assert.are.equal(1, c.numel)
  end)

  it("matrix_rank", function()
    local a = ins.from_table({ { 1.0, 0.0 }, { 0.0, 1.0 } }):to(ins.GPUPlace(0))
    local r = ins.matrix_rank(a)
    assert.is_not_nil(r)
    assert.are.equal(1, r.numel)
  end)

  it("matrix_power", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 } }):to(ins.GPUPlace(0))
    local b = ins.matrix_power(a, 2)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("slogdet", function()
    local a = ins.from_table({ { 1.0, 2.0 }, { 3.0, 4.0 } }):to(ins.GPUPlace(0))
    local s, ld = ins.slogdet(a)
    assert.is_not_nil(s)
    assert.is_not_nil(ld)
  end)

  it("eigvalsh", function()
    local a = ins.from_table({ { 4.0, 2.0 }, { 2.0, 3.0 } }):to(ins.GPUPlace(0))
    local w = ins.eigvalsh(a)
    assert.is_not_nil(w)
    assert.are.equal(2, w.numel)
  end)
end)
