-- Elementwise CUDA binding tests — aligned with C++ test_elementwise.cpp
-- Run with:
--   LUA_PATH="bindings/lua/?/init.lua;;" LUA_CPATH="build/bindings/lua/?.so;;"
--   LD_LIBRARY_PATH=build/backends/cpu:build/backends/cuda
--   ~/.luarocks/bin/busted tests/cuda/lua/test_elementwise.lua

local ok_ins, ins = pcall(require, "_insight")
if not ok_ins then
  print("SKIP: _insight module not available")
  os.exit(0)
end

local ok_gpu = pcall(function()
  ins.init()
end)
if not ok_gpu then
  print("SKIP: GPU backend not available")
  os.exit(0)
end

ins.set_device(ins.GPUPlace(0))

describe("Elementwise CUDA Tests", function()
  it("add", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0, 5.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 5.0, 4.0, 3.0, 2.0, 1.0 }):to(ins.GPUPlace(0))
    local c = ins.add(a, b)
    assert.is_not_nil(c)
    assert.are.equal(5, c.numel)
  end)

  it("sub", function()
    local a = ins.from_table({ 10.0, 20.0, 30.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local c = ins.sub(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("mul", function()
    local a = ins.from_table({ 2.0, 3.0, 4.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 5.0, 6.0, 7.0 }):to(ins.GPUPlace(0))
    local c = ins.mul(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("div", function()
    local a = ins.from_table({ 10.0, 20.0, 30.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 2.0, 4.0, 5.0 }):to(ins.GPUPlace(0))
    local c = ins.div(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("pow", function()
    local a = ins.from_table({ 2.0, 3.0, 4.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 3.0, 2.0, 0.5 }):to(ins.GPUPlace(0))
    local c = ins.pow(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("mod", function()
    local a = ins.from_table({ 10.0, 7.0, 5.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 3.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local c = ins.mod(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("maximum", function()
    local a = ins.from_table({ 1.0, 5.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 4.0, 2.0, 6.0 }):to(ins.GPUPlace(0))
    local c = ins.maximum(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("minimum", function()
    local a = ins.from_table({ 1.0, 5.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 4.0, 2.0, 6.0 }):to(ins.GPUPlace(0))
    local c = ins.minimum(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("equal", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 1.0, 0.0, 3.0 }):to(ins.GPUPlace(0))
    local c = ins.equal(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("not_equal", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 1.0, 0.0, 3.0 }):to(ins.GPUPlace(0))
    local c = ins.not_equal(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("greater", function()
    local a = ins.from_table({ 3.0, 1.0, 5.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 2.0, 4.0, 5.0 }):to(ins.GPUPlace(0))
    local c = ins.greater(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("less", function()
    local a = ins.from_table({ 1.0, 5.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 2.0, 4.0, 5.0 }):to(ins.GPUPlace(0))
    local c = ins.less(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("greater_equal", function()
    local a = ins.from_table({ 3.0, 1.0, 5.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 2.0, 4.0, 5.0 }):to(ins.GPUPlace(0))
    local c = ins.greater_equal(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("less_equal", function()
    local a = ins.from_table({ 1.0, 5.0, 3.0 }):to(ins.GPUPlace(0))
    local b = ins.from_table({ 2.0, 4.0, 5.0 }):to(ins.GPUPlace(0))
    local c = ins.less_equal(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("logical_and", function()
    local a = ins.from_table({ 1, 1, 0 }, ins.bool):to(ins.GPUPlace(0))
    local b = ins.from_table({ 1, 0, 0 }, ins.bool):to(ins.GPUPlace(0))
    local c = ins.logical_and(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("logical_or", function()
    local a = ins.from_table({ 1, 1, 0 }, ins.bool):to(ins.GPUPlace(0))
    local b = ins.from_table({ 1, 0, 0 }, ins.bool):to(ins.GPUPlace(0))
    local c = ins.logical_or(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("logical_xor", function()
    local a = ins.from_table({ 1, 1, 0 }, ins.bool):to(ins.GPUPlace(0))
    local b = ins.from_table({ 1, 0, 0 }, ins.bool):to(ins.GPUPlace(0))
    local c = ins.logical_xor(a, b)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("logical_not", function()
    local a = ins.from_table({ 1, 0, 1 }, ins.bool):to(ins.GPUPlace(0))
    local c = ins.logical_not(a)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)
end)
