-- Manipulation CPU binding tests — aligned with C++ test_manipulation.cpp
-- Run with:
--   LUA_PATH="bindings/lua/?/init.lua;;" LUA_CPATH="build/bindings/lua/?.so;;"
--   LD_LIBRARY_PATH=build/backends/cpu ~/.luarocks/bin/busted tests/cpu/lua/test_manipulation.lua

describe("Manipulation CPU Tests", function()
  local ins
  setup(function()
    ins = require("_insight")
    ins.set_device(ins.CPUPlace())
  end)

  it("reshape", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 })
    local b = a:reshape({ 2, 3 })
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
    assert.are.equal(2, b.ndim)
  end)

  it("transpose", function()
    local a = ins.from_table({ { 1, 2, 3 }, { 4, 5, 6 } })
    local b = ins.permute(a, { 2, 1 })
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
  end)

  it("squeeze", function()
    local a = ins.zeros({ 1, 3, 1 }, ins.float64)
    local b = a:squeeze()
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("unsqueeze", function()
    local a = ins.zeros({ 3 }, ins.float64)
    local b = a:unsqueeze(1)
    assert.is_not_nil(b)
    assert.are.equal(2, b.ndim)
  end)

  it("concat", function()
    local a = ins.from_table({ 1.0, 2.0 })
    local b = ins.from_table({ 3.0, 4.0 })
    local c = ins.concat({ a, b })
    assert.is_not_nil(c)
    assert.are.equal(4, c.numel)
  end)

  it("split", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 })
    local parts = ins.split(a, 3, 1)
    assert.is_not_nil(parts)
    assert.are.equal(3, #parts)
  end)

  it("tile", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 })
    local b = ins.tile(a, ins.Shape({ 2 }))
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
  end)

  it("repeat", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 })
    local b = ins["repeat"](a, 2)
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
  end)

  it("flip", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0 })
    local b = ins.flip(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("roll", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0, 5.0 })
    local b = ins.roll(a, 2)
    assert.is_not_nil(b)
    assert.are.equal(5, b.numel)
  end)

  it("pad", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 })
    local b = ins.pad(a, { 2, 3 })
    assert.is_not_nil(b)
    assert.are.equal(8, b.numel)
  end)

  it("diag", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 })
    local b = ins.diag(a)
    assert.is_not_nil(b)
    assert.are.equal(9, b.numel)
    assert.are.equal(2, b.ndim)
  end)

  it("tril", function()
    local a = ins.ones({ 3, 3 }, ins.float64)
    local b = ins.tril(a)
    assert.is_not_nil(b)
    assert.are.equal(9, b.numel)
  end)

  it("triu", function()
    local a = ins.ones({ 3, 3 }, ins.float64)
    local b = ins.triu(a)
    assert.is_not_nil(b)
    assert.are.equal(9, b.numel)
  end)

  it("diff", function()
    local a = ins.from_table({ 1.0, 3.0, 6.0, 10.0 })
    local b = ins.diff(a)
    assert.is_not_nil(b)
    assert.are.equal(3, b.numel)
  end)

  it("swapaxes", function()
    local a = ins.ones({ 2, 3, 4 }, ins.float64)
    local b = ins.swapaxes(a, 1, 3)
    assert.is_not_nil(b)
    assert.are.equal(24, b.numel)
  end)

  it("moveaxis", function()
    local a = ins.ones({ 2, 3, 4 }, ins.float64)
    local b = ins.moveaxis(a, 1, 3)
    assert.is_not_nil(b)
    assert.are.equal(24, b.numel)
  end)

  it("fliplr", function()
    local a = ins.from_table({ { 1, 2 }, { 3, 4 } })
    local b = ins.fliplr(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("flipud", function()
    local a = ins.from_table({ { 1, 2 }, { 3, 4 } })
    local b = ins.flipud(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("rot90", function()
    local a = ins.from_table({ { 1, 2 }, { 3, 4 } })
    local b = ins.rot90(a)
    assert.is_not_nil(b)
    assert.are.equal(4, b.numel)
  end)

  it("flatten", function()
    local a = ins.ones({ 2, 3 }, ins.float64)
    local b = ins.flatten(a)
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
    assert.are.equal(1, b.ndim)
  end)

  it("ravel", function()
    local a = ins.ones({ 2, 3 }, ins.float64)
    local b = ins.ravel(a)
    assert.is_not_nil(b)
    assert.are.equal(6, b.numel)
    assert.are.equal(1, b.ndim)
  end)

  -- ====================================================================
  -- In-place mutation (fill_, copy_from_)
  -- ====================================================================

  it("fill_ scalar", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0 })
    a:fill_(99.0)
    assert.near(99.0, a:get(0), 1e-10)
    assert.near(99.0, a:get(1), 1e-10)
    assert.near(99.0, a:get(2), 1e-10)
    assert.near(99.0, a:get(3), 1e-10)
  end)

  it("copy_from_ array", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0 })
    local src = ins.from_table({ 10.0, 20.0, 30.0, 40.0 })
    a:copy_from_(src)
    assert.near(10.0, a:get(0), 1e-10)
    assert.near(20.0, a:get(1), 1e-10)
    assert.near(30.0, a:get(2), 1e-10)
    assert.near(40.0, a:get(3), 1e-10)
  end)

  -- ====================================================================
  -- Reshape: -1 inference + error cases
  -- ====================================================================

  it("reshape_infer_neg1_end", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 })
    local b = a:reshape({ 1, -1 })
    assert.are.equal(2, b.ndim)
    assert.are.equal(1, b.shape[1])
    assert.are.equal(6, b.shape[2])
  end)

  it("reshape_infer_neg1_begin", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 })
    local b = a:reshape({ -1, 2 })
    assert.are.equal(2, b.ndim)
    assert.are.equal(3, b.shape[1])
    assert.are.equal(2, b.shape[2])
  end)

  it("reshape_infer_neg1_3d", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 })
    local b = a:reshape({ 2, 3, -1 })
    assert.are.equal(3, b.ndim)
    assert.are.equal(2, b.shape[1])
    assert.are.equal(3, b.shape[2])
    assert.are.equal(2, b.shape[3])
  end)

  it("reshape_neg1_to_1d", function()
    local a = ins.Array({ { 1, 2, 3 }, { 4, 5, 6 } })
    local b = a:reshape({ -1 })
    assert.are.equal(1, b.ndim)
    assert.are.equal(6, b.shape[1])
  end)

  it("reshape_error_mismatch", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 })
    assert.has_error(function()
      a:reshape({ 2, 4 })
    end)
  end)

  it("reshape_error_multiple_neg1", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 })
    assert.has_error(function()
      a:reshape({ -1, -1 })
    end)
  end)

  it("reshape_error_neg1_not_divisible", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5 })
    assert.has_error(function()
      a:reshape({ 2, -1 })
    end)
  end)

  it("reshape_error_zero_dim", function()
    local a = ins.from_table({ 1, 2, 3, 4 })
    assert.has_error(function()
      a:reshape({ 0, 2 })
    end)
  end)

  it("reshape_data_preserved", function()
    local a = ins.from_table({ 1, 2, 3, 4, 5, 6 })
    local b = a:reshape({ 2, 3 })
    -- get() uses flat index
    assert.near(1.0, b:get(0), 1e-10)
    assert.near(2.0, b:get(1), 1e-10)
    assert.near(6.0, b:get(5), 1e-10)
  end)
end)
