-- Indexing and sorting CPU binding tests
-- Run with:
--   LUA_PATH="bindings/lua/?/init.lua;;" LUA_CPATH="build/bindings/lua/?.so;;" \
--   LD_LIBRARY_PATH=build/backends/cpu ~/.luarocks/bin/busted tests/cpu/lua/test_indexing.lua

describe("Indexing CPU Tests", function()
  local ins
  setup(function()
    ins = require("_insight")
    ins.set_device(ins.CPUPlace())
  end)

  it("take 1d", function()
    local a = ins.from_table({ 10.0, 20.0, 30.0, 40.0, 50.0 })
    local idx = ins.from_table({ 0, 2, 4 }, ins.int64)
    local result = ins.take(a, idx)
    assert.is_not_nil(result)
    assert.are.equal(3, result.numel)
  end)

  it("nonzero", function()
    local a = ins.from_table({ 0.0, 1.0, 0.0, 3.0, 0.0 })
    local result = ins.nonzero(a)
    assert.is_not_nil(result)
    assert.is_true(result.numel > 0)
  end)

  it("flatnonzero", function()
    local a = ins.from_table({ 0.0, 1.0, 0.0, 3.0, 0.0 })
    local result = ins.flatnonzero(a)
    assert.is_not_nil(result)
    assert.are.equal(2, result.numel)
  end)

  it("unique 1d", function()
    local a = ins.from_table({ 3.0, 1.0, 2.0, 1.0, 3.0, 2.0 })
    local result = ins.unique(a)
    assert.is_not_nil(result)
    assert.is_true(result.unique.numel >= 1)
  end)

  it("argsort 1d", function()
    local a = ins.from_table({ 3.0, 1.0, 2.0 })
    local result = ins.argsort(a)
    assert.is_not_nil(result)
    assert.are.equal(3, result.numel)
  end)

  it("sort 1d", function()
    local a = ins.from_table({ 3.0, 1.0, 4.0, 1.0, 5.0 })
    local result = ins.sort(a)
    assert.is_not_nil(result)
    assert.are.equal(5, result.numel)
  end)

  it("topk", function()
    local a = ins.from_table({ 1.0, 5.0, 3.0, 2.0, 4.0 })
    local result = ins.topk(a, 3)
    assert.is_not_nil(result)
    assert.are.equal(3, result.numel)
  end)

  it("gather", function()
    local a = ins.from_table({ { 10.0, 20.0 }, { 30.0, 40.0 } })
    local idx = ins.from_table({ { 0, 1 }, { 1, 0 } }, ins.int64)
    local result = ins.gather(a, 1, idx)
    assert.is_not_nil(result)
    assert.are.equal(4, result.numel)
  end)

  it("scatter", function()
    local a = ins.zeros({ 4 }, ins.float64)
    local idx = ins.from_table({ 0, 2 }, ins.int64)
    local src = ins.from_table({ 10.0, 20.0 })
    local result = ins.scatter(a, 1, idx, src)
    assert.is_not_nil(result)
    assert.are.equal(4, result.numel)
  end)

  it("scatter_add", function()
    local a = ins.zeros({ 4 }, ins.float64)
    local idx = ins.from_table({ 0, 0, 2 }, ins.int64)
    local src = ins.from_table({ 1.0, 2.0, 3.0 })
    local result = ins.scatter_add(a, 1, idx, src)
    assert.is_not_nil(result)
    assert.are.equal(4, result.numel)
  end)

  it("searchsorted", function()
    local sorted = ins.from_table({ 1.0, 3.0, 5.0, 7.0 })
    local values = ins.from_table({ 2.0, 5.0, 8.0 })
    local result = ins.searchsorted(sorted, values)
    assert.is_not_nil(result)
    assert.are.equal(3, result.numel)
  end)

  it("interp", function()
    local xp = ins.from_table({ 0.0, 1.0, 2.0, 3.0 })
    local fp = ins.from_table({ 0.0, 2.0, 4.0, 6.0 })
    local x = ins.from_table({ 0.5, 1.5, 2.5 })
    local result = ins.interp(x, xp, fp)
    assert.is_not_nil(result)
    assert.are.equal(3, result.numel)
  end)

  it("masked_select", function()
    local a = ins.from_table({ 10.0, 20.0, 30.0, 40.0, 50.0 })
    local mask = ins.from_table({ 1, 0, 1, 0, 1 }, ins.bool)
    local result = ins.masked_select(a, mask)
    assert.is_not_nil(result)
    assert.are.equal(3, result.numel)
  end)

  it("sort 2d", function()
    local a = ins.from_table({ { 3.0, 1.0 }, { 2.0, 4.0 } })
    local result = ins.sort(a)
    assert.is_not_nil(result)
    assert.are.equal(4, result.numel)
  end)

  it("argsort 2d", function()
    local a = ins.from_table({ { 3.0, 1.0 }, { 2.0, 4.0 } })
    local result = ins.argsort(a)
    assert.is_not_nil(result)
    assert.are.equal(4, result.numel)
  end)

  it("topk smallest", function()
    local a = ins.from_table({ 1.0, 5.0, 3.0, 2.0, 4.0 })
    local result = ins.topk(a, 3, -1, false)
    assert.is_not_nil(result)
    assert.are.equal(3, result.numel)
  end)

  it("scatter_reduce add", function()
    local a = ins.zeros({ 4 }, ins.float64)
    local idx = ins.from_table({ 0, 0, 2 }, ins.int64)
    local src = ins.from_table({ 1.0, 2.0, 3.0 })
    local result = ins.scatter_reduce(a, 1, idx, src, "add")
    assert.is_not_nil(result)
    assert.are.equal(4, result.numel)
  end)
end)
